# EduForge — Windows PowerShell Setup & Run Script
# Run with: .\scripts\setup_windows.ps1
# Requires: Python 3.10, Docker Desktop (running), Git

param(
    [switch]$SkipDocker,
    [switch]$DevMode,
    [switch]$InstallDeps
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "   EduForge — Windows Setup Script" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

Set-Location $ProjectRoot

# ── 1. Python Version Check ───────────────────────────────────────────────────
Write-Host "[1/7] Checking Python..." -ForegroundColor Yellow
$pyVersion = python --version 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Python not found. Install Python 3.10 from python.org" -ForegroundColor Red
    exit 1
}
Write-Host "      $pyVersion" -ForegroundColor Green

# ── 2. Create virtual environment ─────────────────────────────────────────────
Write-Host "[2/7] Setting up virtual environment..." -ForegroundColor Yellow
if (-not (Test-Path ".venv")) {
    python -m venv .venv
    Write-Host "      Created .venv" -ForegroundColor Green
} else {
    Write-Host "      .venv already exists" -ForegroundColor Green
}

# Activate venv
& ".\.venv\Scripts\Activate.ps1"
Write-Host "      Activated .venv" -ForegroundColor Green

# ── 3. Install dependencies ────────────────────────────────────────────────────
if ($InstallDeps) {
    Write-Host "[3/7] Installing Python dependencies..." -ForegroundColor Yellow
    pip install --upgrade pip --quiet
    pip install -r requirements.txt --quiet
    Write-Host "      Dependencies installed" -ForegroundColor Green
} else {
    Write-Host "[3/7] Skipping pip install (use -InstallDeps to install)" -ForegroundColor Gray
}

# ── 4. Create .env file ────────────────────────────────────────────────────────
Write-Host "[4/7] Creating .env file..." -ForegroundColor Yellow
if (-not (Test-Path ".env")) {
    @"
# EduForge Environment Configuration
# Generated by setup_windows.ps1 — edit as needed

ENV=development
DEBUG=false
LOG_LEVEL=INFO
SECRET_KEY=dev-secret-key-change-in-production-$(Get-Random)

# Database (Docker)
DATABASE_URL=postgresql://eduforge:eduforge@localhost:5432/eduforge

# Redis (Docker)
REDIS_URL=redis://localhost:6379/0
CELERY_BROKER_URL=redis://localhost:6379/1
CELERY_RESULT_BACKEND=redis://localhost:6379/2

# ChromaDB (Docker)
CHROMA_HOST=localhost
CHROMA_PORT=8100

# MLflow (Docker)
MLFLOW_TRACKING_URI=http://localhost:5000

# Models (will download on first use)
EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
GENERATION_MODEL=google/flan-t5-small

# Upload limits
MAX_FILE_SIZE_MB=50
"@ | Out-File -FilePath ".env" -Encoding UTF8
    Write-Host "      .env created" -ForegroundColor Green
} else {
    Write-Host "      .env already exists — skipping" -ForegroundColor Green
}

# ── 5. Create data directories ─────────────────────────────────────────────────
Write-Host "[5/7] Creating data directories..." -ForegroundColor Yellow
@("data\raw", "data\processed", "data\models") | ForEach-Object {
    New-Item -ItemType Directory -Force -Path $_ | Out-Null
}
Write-Host "      Directories ready" -ForegroundColor Green

# ── 6. Start Docker services ──────────────────────────────────────────────────
if (-not $SkipDocker) {
    Write-Host "[6/7] Starting Docker services..." -ForegroundColor Yellow

    # Check Docker is running
    $dockerInfo = docker info 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host "      WARNING: Docker not running — start Docker Desktop first" -ForegroundColor Red
        Write-Host "      Skipping Docker startup..." -ForegroundColor Yellow
    } else {
        Write-Host "      Docker is running" -ForegroundColor Green
        Write-Host "      Starting: postgres, redis, chromadb, mlflow..." -ForegroundColor Yellow

        docker compose up -d postgres redis chromadb mlflow 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Host "      Waiting 15s for services to initialise..." -ForegroundColor Yellow
            Start-Sleep -Seconds 15
            Write-Host "      Docker services started" -ForegroundColor Green
        } else {
            Write-Host "      WARNING: Docker compose failed — check Docker Desktop" -ForegroundColor Red
        }
    }
} else {
    Write-Host "[6/7] Skipping Docker (use without -SkipDocker to start)" -ForegroundColor Gray
}

# ── 7. Run setup CLI ──────────────────────────────────────────────────────────
Write-Host "[7/7] Running system setup..." -ForegroundColor Yellow
python scripts/cli.py setup
if ($LASTEXITCODE -eq 0) {
    Write-Host "      Setup complete" -ForegroundColor Green
} else {
    Write-Host "      WARNING: Setup failed (DB may not be running yet)" -ForegroundColor Yellow
    Write-Host "      Run manually: python scripts/cli.py setup" -ForegroundColor Yellow
}

# ── Summary ───────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "   EduForge Setup Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor White
Write-Host ""
Write-Host "  Start API:" -ForegroundColor Yellow
Write-Host "    uvicorn services.gateway.main:app --reload --host 0.0.0.0 --port 8000" -ForegroundColor White
Write-Host ""
Write-Host "  Start UI:" -ForegroundColor Yellow
Write-Host "    streamlit run ui/dashboard.py" -ForegroundColor White
Write-Host ""
Write-Host "  Check system status:" -ForegroundColor Yellow
Write-Host "    python scripts/cli.py status" -ForegroundColor White
Write-Host ""
Write-Host "  Seed demo data:" -ForegroundColor Yellow
Write-Host "    python scripts/cli.py seed" -ForegroundColor White
Write-Host ""
Write-Host "  Run tests:" -ForegroundColor Yellow
Write-Host "    pytest tests/ -v --cov=. --cov-report=term-missing" -ForegroundColor White
Write-Host ""
Write-Host "  API docs:" -ForegroundColor Yellow
Write-Host "    http://localhost:8000/docs" -ForegroundColor White
Write-Host ""
Write-Host "  Grafana dashboard:" -ForegroundColor Yellow
Write-Host "    http://localhost:3000  (admin / admin)" -ForegroundColor White
Write-Host ""
Write-Host "  MLflow UI:" -ForegroundColor Yellow
Write-Host "    http://localhost:5000" -ForegroundColor White
Write-Host ""

if ($DevMode) {
    Write-Host "  Starting API in dev mode..." -ForegroundColor Cyan
    uvicorn services.gateway.main:app --reload --host 0.0.0.0 --port 8000
}
